improve ux: add note-search script; add 'workon' script; clean up env setup on system start

diff --git a/scripts/.local/bin/search_dev_notes b/scripts/.local/bin/search_dev_notes
--- a/scripts/.local/bin/search_dev_notes
+++ b/scripts/.local/bin/search_dev_notes
@@ -1,30 +1,51 @@
+#!/usr/bin/env bash
+
 # script to alleviate friction in this workflow:
 # - be doing something
 # - "how do I {do this in typst/bash/whatever}?"
 
 # it would be nice to be able to easily search through dev notes at this point.
 
-here's ppl talking about searching both filenames and contents 
-using fzf and rg
-https://github.com/junegunn/fzf/issues/2789
+# here's ppl talking about searching both filenames and contents
+# https://github.com/junegunn/fzf/issues/2789
 
-most upvoted snippet:
-# rg
-  # --field-match-separator ' ' - tell rg to separate the filename and linenumber with
-  # spaces to play well with fzf, (when recognizing index variables to use in the fzf
-  # preview command, fzf uses a default delimiter of space, see below)
+SEARCH_PATH=${1:-$DEV_DOCS}
+SEARCH_PATH=${SEARCH_PATH:-"/home/tom/docs"}
 
-# fzf
-  # --preview window ~8,+{1}-5
-  #   this is a fzf feature
-  #   ~8 - show first 8 lines (header)
-  #   +{2} - fzf delimits the input piped in to it and provides access via index variables {n}. 
-  #   the default delimiter fzf uses is space but can be specified via --delimiter <delimiter>
-  #   pass the second index variable from bat (which is the line number)
-  #   the number is signed, you can show eg the +n row or the -n row (the nth row from the bottom)
-  #   -5 subtract 5 rows (go up 5 rows) so that you don't show the highlighted line as the first line
-  #   since you want to provide context by showing the rows above the highlighted line
+_search() {
+  cd "$SEARCH_PATH" || exit
+  # 1. Search for text in files using Ripgrep
+  # 2. Interactively restart Ripgrep with reload action
+  # 3. Open the file in Vim
+  RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
+  INITIAL_QUERY="${*:-}"
+  fzf --ansi --disabled --query "$INITIAL_QUERY" \
+    --bind "start:reload:$RG_PREFIX {q} . || true" \
+    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} . || true" \
+    --delimiter ":" \
+    --cycle \
+    --with-nth 1,2,4 \
+    --layout=reverse \
+    --border=rounded \
+    --color='bg+:#333c43,bg:-1,hl:yellow,fg:-1,header:green,info:cyan,pointer:yellow,marker:yellow,fg+:white,prompt:cyan,hl+:yellow:underline' \
+    --preview 'bat --theme="zenburn" --color=always {1} --highlight-line {2}' \
+    --preview-window 'right,60%,border-left,+{2}+3/3,~3' \
+    --bind 'enter:become(nvim {1} +{2})' \
+    --bind "alt-n:down,alt-p:up"
+}
+# --color="bg+:#32302f,bg:#282828,hl:#d79921,fg" \
+# --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
 
-rg --line-number --with-filename . --color=always --field-match-separator ' '\
-  | fzf --preview "bat --color=always {1} --highlight-line {2}" \
-  --preview-window ~8,+{2}-5
+# check if launched from term or via hotkey
+# method: is stdin attached to term?
+if [ -t 0 ]; then
+  # I am already in a terminal, just run.
+  _search "$@" && exit 0
+
+else
+  # I am floating in the void, launch a terminal + myself.
+  st -t "The Brain" -c "brain" -g 140x40 -e "$0" "$@" && exit 0
+fi
+
+echo 'ERROR'
+exit 1
